### ISSUE TITLE
Does the script work without the cmake patch?

### ISSUE THREAD

**Issue by adamryczkowski** [volo-zyko/cmake-profile-stats#2]
I get all the lines "ignored"

**Comment by fwinkl** [comment]
No the script will not work without the patch. 

@volo-zyko this script is really extremely useful for profiling large projects. Did you consider proposing a patch to cmake upstream? I am pretty sure this would get included (possibly via an extra command line option).

**Comment by volo-zyko** [comment]
Somehow I missed this ticket. Sorry. @fwinkl is right, the script doesn't work without the patch.

No, I didn't send a PR with this patch to the cmake upstream. From my experience (I fixed a couple of bugs in cmake) they are rather strict about what they accept. So, I doubt that they will accept this change.

Probably they will want some profiling facility on their side and I'm 100% sure they would implement it differently. :) I consider this script a hack.

**Comment by fwinkl** [comment]
By coincidence cmake just introduced a json-based trace format to be released with 3.17. Let's see if they accept to add the timestamp and frame number: https://gitlab.kitware.com/cmake/cmake/merge_requests/4242

**Comment by volo-zyko** [comment]
Cool, I didn't know about that new trace format. It's very likely that they will accept the change. :) That's pretty cool. I'll check/adjust my script for working with this new feature.

**Comment by fwinkl** [comment]
cmake 3.17.0-rc1 contains the new json trace output format. Would be great if you could adapt your script.

**Comment by volo-zyko** [comment]
Thanks for the reminder. I know that you added this feature. Concerning the script, I changed it but didn't have time to test it properly.
